// const language = {
//     english: [
//         'About Me',
//         'Projects',
//         'Português',
//         'Contact',
//         'Navigation',
//         'About Me',
//         'Projects',
//         'Theme',
//         'Language',
//         'Português',
//         'Your email was sent successfully!',
//         'Contact',
//         'Interested in working together? Send me an email!',
//         'Name',
//         'Subject',
//         'Message',
//         'About Me',
//         "My name is Luiz Felyppe and I'm a full-stack programmer. I'm currently doing bachelor in Information Systems at UFF (Fluminense Federal University) and I work at ",
//         "Focused on the web development field, I'm in love with technology and I'm constantly learning in order to improve my programming abilities.",
//         'Technologies',
//         'Projects',
//         'A coffee e-commerce proposed as a challange in the Rocketseat course. This project was made to learn concepts of React JS and TypeScript.',
//         'Source code',
//         'Authentication System',
//         'A login system made in ReactJS and NodeJS using JsonWebToken with a refresh token to combine security with a seamless user experience, and ensuring session persistence.',
//         'Source code',
//         'Calculator',
//         'A copy of a calculator I have at home with pretty much the same functionalities. Project made to practice JavaScript',
//         'Source code',
//         'To-do List',
//         'A to-do list for you not to forget your tasks! This project was made in the Rocketseat course and it was my first one using React JS.',
//         'Source code',
//         'Paginated Form',
//         "A multi-step form that I've done to practice user input validations using the zod library (I haven't been programming in React).",
//         'Source code',
//         'Soon'
//     ],
//     portuguese: [
//         'Sobre Mim',
//         'Projetos',
//         'English',
//         'Contato',
//         'Navegação',
//         'Sobre Mim',
//         'Projetos',
//         'Tema',
//         'Idioma',
//         'English',   
//         'Seu email foi enviado com sucesso!', 
//         'Contato',
//         'Interessado em trabalharmos juntos? Me envie um email!',
//         'Nome',
//         'Assunto',
//         'Mensagem',
//         'Sobre Mim',
//         "Meu nome é Luiz Felyppe e eu sou programador full-stack. Atualmente, faço Sistemas de Informação na UFF (Universidade Federal Fluminense) e trabalho na ",
//         "Focado na área de desenvolvimento web, sou apaixonado por tecnologia e estou em constante aprendizado visando a melhorar minhas habilidades na programação.",
//         'Tecnologias',
//         'Projetos',
//         'Um e-commerce de cafés proposto como desafio no curso da Rocketseat. Esse projeto foi realizado para fixar conceitos de React JS com TypeScript.',
//         'Código fonte',
//         'Sistema de Autenticação',
//         'Um sistema de login feito em ReactJS e NodeJS utilizando JsonWebToken com refresh token para unir segurança com uma experiência contínua, além de ter persistência da sessão.',
//         'Código fonte',
//         'Calculadora',
//         'A réplica de uma calculadora que tenho em casa com praticamente as mesmas funcionalidades. Na próxima versão estará completa. Projeto realizado para praticar JavaScript.',
//         'Código fonte',
//         'Lista de afazeres',
//         'Uma lista de afazeres para você não esquecer das suas tarefas! Esse projeto foi feito no curso da Rocketseat e foi o meu primeiro usando React JS.',
//         'Código fonte',
//         'Formulário Paginado',
//         'Um formulário multietapas qualquer que eu fiz para treinar validações de input do usuário usando a biblioteca zod (estava sem programar em React).',
//         'Código fonte',
//         'Em breve'
//     ]
// }

const language = {
    english: {
        '0': 'About Me',
        '1': 'Projects',
        '2': 'English',
        '3': 'Contact',
        '4': 'Navigation',
        '5': 'About Me',
        '6': 'Projects',
        '7': 'Theme',
        '8': 'Language',
        '9': 'English',
        '10': 'Your email was sent successfully!',
        '11': 'Contact',
        '12': 'Interested in working together? Send me an email!',
        '13': 'Name',
        '14': 'Subject',
        '15': 'Message',
        '16': 'About Me',
        '17': "My name is Luiz Felyppe and I'm a full-stack developer. I'm currently doing bachelor in Information Systems at UFF (Fluminense Federal University) and I work at ",
        '18': "I'm focused on software and data engineering, areas in which I've been specializing. I always seek to improve my knowledge and contribute with quality solutions.",
        '19': 'Technologies',
        '20': 'Projects',
        '21': 'A coffee e-commerce proposed as a challange in the Rocketseat course. This project was made to learn concepts of React JS and TypeScript.',
        '22': 'Source code',
        '23': 'Authentication System',
        '24': 'A login system made in ReactJS and NodeJS using JsonWebToken with a refresh token to combine security with a seamless user experience, and ensuring session persistence.',
        '25': 'Source code',
        '26': 'Calculator',
        '27': 'A copy of a calculator I have at home with pretty much the same functionalities. Project made to practice JavaScript',
        '28': 'Source code',
        '29': 'To-do List',
        '30': 'A to-do list for you not to forget your tasks! This project was made in the Rocketseat course and it was my first one using React JS.',
        '31': 'Source code',
        '32': 'Paginated Form',
        '33': "A multi-step form that I've done to practice user input validations using the zod library (I haven't been programming in React).",
        '34': 'Source code',
        '35': 'Soon',
        '36': 'Send',
        '37': 'Pandemic Game',
        '38': 'The implementation of the Pandemic board game, with the main mechanics of the original game, made to apply Object Oriented Programming concepts.',
        '39': 'Source code',
        '40': 'CineTicket',
        '41': 'A cinema website (not finished) made in ReactJS and NodeJS following SOLID principles, with automated tests, documentation of endpoints, among others.',
        '42': 'Source code'
    },
    portuguese: {
        '0': 'Sobre Mim',
        '1': 'Projetos',
        '2': 'Português',
        '3': 'Contato',
        '4': 'Navegação',
        '5': 'Sobre Mim',
        '6': 'Projetos',
        '7': 'Tema',
        '8': 'Idioma',
        '9': 'Português',
        '10': 'Seu email foi enviado com sucesso!',
        '11': 'Contato',
        '12': 'Interessado em trabalharmos juntos? Me envie um email!',
        '13': 'Nome',
        '14': 'Assunto',
        '15': 'Mensagem',
        '16': 'Sobre Mim',
        '17': "Meu nome é Luiz Felyppe e sou desenvolvedor full-stack. Atualmente, curso Sistemas de Informação na Universidade Federal Fluminense (UFF) e atuo na ",
        '18': "Tenho foco em engenharia de software e de dados, áreas nas quais venho me especializando. Busco sempre aprimorar meu conhecimento e contribuir com soluções de qualidade.",
        '19': 'Tecnologias',
        '20': 'Projetos',
        '21': 'Um e-commerce de cafés proposto como desafio no curso da Rocketseat. Esse projeto foi realizado para fixar conceitos de React JS com TypeScript.',
        '22': 'Código fonte',
        '23': 'Sistema de Autenticação',
        '24': 'Um sistema de login feito em ReactJS e NodeJS utilizando JsonWebToken com refresh token para unir segurança com uma experiência contínua, além de ter persistência da sessão.',
        '25': 'Código fonte',
        '26': 'Calculadora',
        '27': 'A réplica de uma calculadora que tenho em casa com praticamente as mesmas funcionalidades. Na próxima versão estará completa. Projeto realizado para praticar JavaScript.',
        '28': 'Código fonte',
        '29': 'Lista de afazeres',
        '30': 'Uma lista de afazeres para você não esquecer das suas tarefas! Esse projeto foi feito no curso da Rocketseat e foi o meu primeiro usando React JS.',
        '31': 'Código fonte',
        '32': 'Formulário Paginado',
        '33': 'Um formulário multietapas qualquer que eu fiz para treinar validações de input do usuário usando a biblioteca zod (estava sem programar em React).',
        '34': 'Código fonte',
        '35': 'Em breve',
        '36': 'Enviar',
        '37': 'Jogo Pandemic',
        '38': 'A implementação do jogo de tabuleiro Pandemic, com as principais mecânicas do jogo original, feito para aplicar conceitos de Programação Orientada a Objetos.',
        '39': 'Código fonte',
        '40': 'CineTicket',
        '41': 'Um site de cinema (não finalizado) feito em ReactJS e NodeJS seguindo princípios SOLID, com testes automatizados, documentação dos endpoints, entre outros.',
        '42': 'Código fonte'
    }
}