const language = {
    english: [
        'About Me',
        'Projects',
        'Português',
        'Contact',
        'Navigation',
        'About Me',
        'Projects',
        'Theme',
        'Language',
        'Português',
        'Your email was sent successfully!',
        'Contact',
        'Interested in working together? Send me an email!',
        'Name',
        'Subject',
        'Message',
        'About Me',
        "My name is Luiz Felyppe and I'm a full-stack programmer. I'm currently doing bachelor in Information Systems at UFF (Fluminense Federal University) and I work at ",
        "Focused on the web development field, I'm in love with technology and I'm constantly learning in order to improve my programming abilities.",
        'Technologies',
        'Projects',
        'A coffee e-commerce proposed as a challange in the Rocketseat course. This project was made to learn concepts of React JS and TypeScript.',
        'Source code',
        'Authentication System',
        'A login system made in ReactJS and NodeJS using JsonWebToken with a refresh token to combine security with a seamless user experience, and ensuring session persistence.',
        'Source code',
        'Calculator',
        'A copy of a calculator I have at home with pretty much the same functionalities. Project made to practice JavaScript',
        'Source code',
        'To-do List',
        'A to-do list for you not to forget your tasks! This project was made in the Rocketseat course and it was my first one using React JS.',
        'Source code',
        'Paginated Form',
        "A multi-step form that I've done to practice user input validations using the zod library (I haven't been programming in React).",
        'Source code',
        'Soon'
    ],
    portuguese: [
        'Sobre Mim',
        'Projetos',
        'English',
        'Contato',
        'Navegação',
        'Sobre Mim',
        'Projetos',
        'Tema',
        'Idioma',
        'English',   
        'Seu email foi enviado com sucesso!', 
        'Contato',
        'Interessado em trabalharmos juntos? Me envie um email!',
        'Nome',
        'Assunto',
        'Mensagem',
        'Sobre Mim',
        "Meu nome é Luiz Felyppe e eu sou programador full-stack. Atualmente, faço Sistemas de Informação na UFF (Universidade Federal Fluminense) e trabalho na ",
        "Focado na área de desenvolvimento web, sou apaixonado por tecnologia e estou em constante aprendizado visando a melhorar minhas habilidades na programação.",
        'Tecnologias',
        'Projetos',
        'Um e-commerce de cafés proposto como desafio no curso da Rocketseat. Esse projeto foi realizado para fixar conceitos de React JS com TypeScript.',
        'Código fonte',
        'Sistema de Autenticação',
        'Um sistema de login feito em ReactJS e NodeJS utilizando JsonWebToken com refresh token para unir segurança com uma experiência contínua, além de ter persistência da sessão.',
        'Código fonte',
        'Calculadora',
        'A réplica de uma calculadora que tenho em casa com praticamente as mesmas funcionalidades. Na próxima versão estará completa. Projeto realizado para praticar JavaScript.',
        'Código fonte',
        'Lista de afazeres',
        'Uma lista de afazeres para você não esquecer das suas tarefas! Esse projeto foi feito no curso da Rocketseat e foi o meu primeiro usando React JS.',
        'Código fonte',
        'Formulário Paginado',
        'Um formulário multietapas qualquer que eu fiz para treinar validações de input do usuário usando a biblioteca zod (estava sem programar em React).',
        'Código fonte',
        'Em breve'
    ]
}